site_name: AI集群运维开发文档

# Repository
repo_name: 'Rhyssiyan/sist_ops_doc'
repo_url: 'https://github.com/Rhyssiyan/sist_ops_doc'

nav:
    - 首页: index.md
    - 集群: cluster.md
    - AI集群: aicluster.md
    - 运维基础: basics.md
theme:
  name: material
  highlightjs: true
  hljs_languages:
      - yaml
      - rust
      - bash
  palette:
    primary: 'teal'
    accent: 'red'


dev_addr: 10.19.124.11:3333


markdown_extensions:
  - admonition
  - codehilite:
#      guess_lang: false
      linenums: false
  - toc:
      permalink: true

extra:
    version: 1.0
